### PR TITLE
Automated native_function_invocation fixes

### PR DESCRIPTION
**Pull request by draco2003**
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix ./ --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)

Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

### CODE REVIEW

**Comment by adriansuter** [comment]
Do you have a solution to be able to force a result of a native php function in a php unit test? There are some native functions that can, for example, return false in circumstances that are not easily reproducible - or that are not even clearly defined in the docs. Sometimes all we know is "returns false in case of an error".

**Comment by l0gicgate** [comment]
I don't think this is necessary to be honest. We've already been over this issue in the past. It makes it complicated with our test suite. This is purely for the sake of benchmark numbers, which I don't really care about.

**Comment by draco2003** [comment]
At High traffic volumes this micro optimization definitely adds up.
Was just attempting to push some things upstream to libraries we use. 
No obligation to pull in, we're investigating running this particular fix against all vendor libraries as part of a build process to account for libraries that don't want these changes.

**Comment by l0gicgate** [comment]
@draco2003 if you fixed the failing tests, I might be inclined to merging.

**Comment by draco2003** [comment]
I'll take a look into the failing tests for sure. 

One alternative syntax (just wasn't available in my automated fixer) is the 
use function is_array;

If that would be preferable from a readability perspective, happy to scrap this one and put in a PR with that syntax

**Pull request closed without merging**
