### PR TITLE
Add support for PHP 7.4

### PR DESCRIPTION
**Pull request by theodorejb**
In PHP 7.4 errors are reported for stream read and write operations per
https://github.com/php/php-src/commit/d59aac58b3e7da7ad01a194fe9840d89725ea229.

Tested with PHP 7.4 beta 4.

### CODE REVIEW

**Comment by l0gicgate** [comment]
Is this a WIP? If so please label the title with [WIP]. 

Please fix PHP Stan errors as well

**Comment by theodorejb** [comment]
This isn't a WIP anymore. I fixed the PHPStan errors.

**Comment by l0gicgate** [comment]
We need to add PHP 7.4 to the travis config also, so we can see if the build passes for that version

**Comment by theodorejb** [comment]
I had to allow failures for PHP 7.4 in Travis. One test fails since https://github.com/phpspec/prophecy/pull/432 hasn't been merged yet.

**Comment by l0gicgate** [comment]
> I had to allow failures for PHP 7.4 in Travis. One test fails since phpspec/prophecy#432 hasn't been merged yet.

We'll have to make sure we update prophecy as soon as that's merged and remove the `allow_failure`

**Pull request merged**
