### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by williamdes**
About 966d0fffd845a4e63a69fb157ed4e77b0ab1041b it is similar to https://github.com/phpmyadmin/sql-parser/commit/a20131487496892d4111c1cbe0025fee35180cce 
In Debian we need the tests folder to run auto-package tests on packages.
Example: https://salsa.debian.org/php-team/pear/php-zumba-json-serializer/-/jobs/3521669#L312 or https://ci.debian.net/data/autopkgtest/unstable/amd64/p/phpmyadmin-sql-parser/27794800/log.gz

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @l0gicgate 

Can you review this in priority before the next release please ?
It is really important for me to be able to import your library into Debian: https://salsa.debian.org/php-team/pear/php-slim-psr7

And be able to package it. I can package it without tests, but you know it's not safe for end users, etc..

**Comment by l0gicgate** [comment]
@williamdes sorry I haven't seen this sooner. For some reason it's not letting me run this PR in CI. Would you be able to close and re-open?

**Comment by l0gicgate** [comment]
@williamdes it appears that php nightly is not supported by our downstream dependencies at the moment. I don't mind having CI run against nightly but it makes it look like the PR is failing when it should not.

@akrabat  any thoughts on this? Should we run against nightly on our other repos too or only add when we know our downstream deps have caught up?

**Comment by akrabat** [comment]
The PHP nightly test should be configured in our workflow to be allowed to fail really.

**Comment by akrabat** [comment]
The other changes in the PR look good to me.

**Comment by l0gicgate** [comment]
@akrabat unfortunately github actions don’t support us to allow failure 😕 

There’s a long-standing issue about this that I’ve been tracking since 2020:
https://github.com/actions/runner/issues/2347

I don’t mind adding it, it’ll look like every PR is failing though.

**Comment by akrabat** [comment]
Ah, right. Yes, this is fine as we can set the branch rules to allow merge regardless of whether nightly passes or not.

**Review by akrabat — APPROVED** [review]

**Comment by akrabat** [comment]
Thanks @williamdes. Sorry that it took so long to get merged.

**Comment by williamdes** [comment]
thank you for merging this, it will help for the Debian packaging
It joined Debian with success: https://tracker.debian.org/pkg/php-slim-psr7
🎉

**Pull request merged**
