### PR TITLE
Update phpstan to 0.10

### PR DESCRIPTION
**Pull request by danopz**
Port of slimphp/Slim-Http#63

- updated phpstan
- fixed some logged errors
- its only installed for php 7.1 on travis because we require at least 7.0, but phpstan is at 7.1

### CODE REVIEW

**Comment by akrabat** [comment]
How should we handle PHPStan for local development?

**Comment by akrabat** [comment]
Thanks @danopz 

I've now enabled Travis on this repo

**Comment by danopz** [comment]
Personally I would be in favor of going with PHP 7.1

**Comment by akrabat** [comment]
Let's do that then.

**Pull request merged**
